name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.0.0-rc.2
        with:
          command: lint

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0-rc.1
        if: steps.lint.outputs.changed == 'true'

      - name: Create argocd namespace for argoconfig chart
        run: kubectl create ns argocd

      - name: Install Argo CD Application CRD
        run: kubectl apply -f https://raw.githubusercontent.com/argoproj/argo-cd/v1.5.2/manifests/crds/application-crd.yaml

      - name: Install Argo CD AppProject CRD
        run: kubectl apply -f https://raw.githubusercontent.com/argoproj/argo-cd/v1.5.2/manifests/crds/appproject-crd.yaml

      - name: Install ServiceMonitor CRD
        run: kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/release-0.38/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml

      - name: Install PodMonitor CRD
        run: kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/release-0.38/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml

      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.0.0-rc.2
        with:
          command: install
